//--------------------------------------------------------------------------
// File:	bull_names.h
// Source:	Generated by SlkRip
// Copyright:	Copyright Nov 21 2000 - Saffire Corporation.
//		All Rights Reserved.
//--------------------------------------------------------------------------
// bull_names.h
//--------------------------------------------------------------------------

#ifndef _BULL_NAMES_H_
#define _BULL_NAMES_H_ 1


#define CHARACTER_BULL   	1651862636
#define BULL_IDLE        	1651257392
#define BULL_WALK        	1651257393
#define BULL_RUN         	1651257394
#define BULL_JUMP_TAKEOFF	1651257395
#define BULL_JUMP_STALL  	1651257396
#define BULL_JUMP_LAND   	1651257397
#define BULL_IDLE_2      	1651257398
#define BULL_CHARGE      	1651257399
#define BULL_START_CHARGE	1651257400
#define BULL_REAR_UP     	1651257401


#endif _BULL_NAMES_H_
