//--------------------------------------------------------------------------
// File:	imon_names.h
// Source:	Generated by SlkRip
// Copyright:	Copyright Nov 21 2000 - Saffire Corporation.
//		All Rights Reserved.
//--------------------------------------------------------------------------
// imon_names.h
//--------------------------------------------------------------------------

#ifndef _IMON_NAMES_H_
#define _IMON_NAMES_H_ 1


#define CHARACTER_IMON  	1768779630
#define IMON_IDLE       	1768763440
#define IMON_SMASH_RIGHT	1768763443
#define IMON_SMASH_LEFT 	1768763444
#define IMON_LAUGH      	1768763442
#define IMON_SMASH_BOTH 	1768763446
#define IMON_OUCH       	1768763445


#endif _IMON_NAMES_H_
