//--------------------------------------------------------------------------
// File:	btfr_names.h
// Source:	Generated by SlkRip
// Copyright:	Copyright Apr  4 2001 - Saffire Corporation.
//		All Rights Reserved.
//--------------------------------------------------------------------------
// btfr_names.h
//--------------------------------------------------------------------------

#ifndef _BTFR_NAMES_H_
#define _BTFR_NAMES_H_ 1


#define CHARACTER_BTFR 	1651795570
#define BATS_GLIDE     	1651781685
#define BATS_FLAP      	1651781684
#define BATS_HIT       	1651781686
#define BATS_STUN      	1999646771
#define BATS_SLAP      	1651781683
#define BATS_FLY_ATTACK	1651781682


#endif _BTFR_NAMES_H_
