//--------------------------------------------------------------------------
// File:	rptl_names.h
// Source:	Generated by SlkRip
// Copyright:	Copyright Apr  4 2001 - Saffire Corporation.
//		All Rights Reserved.
//--------------------------------------------------------------------------
// rptl_names.h
//--------------------------------------------------------------------------

#ifndef _RPTL_NAMES_H_
#define _RPTL_NAMES_H_ 1


#define CHARACTER_RPTL	1919972460
#define RPTL_IDLE     	1919954992
#define RPTL_WALK     	1919954993
#define RPTL_LPUNCH   	1919954994
#define RPTL_RPUNCH   	1919954995
#define RPTL_BPUNCH   	1919954996
#define RPTL_ROAR     	1919954997
#define RPTL_BOXIDLE  	1919954998


#endif _RPTL_NAMES_H_
