//--------------------------------------------------------------------------
// File:	dfly_names.h
// Source:	Generated by SlkRip
// Copyright:	Copyright Nov 21 2000 - Saffire Corporation.
//		All Rights Reserved.
//--------------------------------------------------------------------------
// dfly_names.h
//--------------------------------------------------------------------------

#ifndef _DFLY_NAMES_H_
#define _DFLY_NAMES_H_ 1


#define CHARACTER_DFLY      	1836282228
#define DFLY_IDLE_LANDED    	1836265522
#define DFLY_TAKEOFF        	1836265523
#define DFLY_FLY            	1836265524
#define DFLY_LAND           	1836265525
#define DFLY_REACT          	1836265527
#define DFLY_SPIT_FIREBALL_1	1836265528
#define DFLY_SPIT_FIREBALL_2	1836265529


#endif _DFLY_NAMES_H_
